name: Cypress_LambdaTest Build
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Steps represent a sequence of tasks that will be executed as part of the job
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: NPM with Cypress
        run : npm config set legacy-peer-deps true
      - name: Install NPM
        run: npm install

      - name: Cupress run
        uses: cypress-io/github-action@v4
        with:
          path: Cypress_LambdaTest/lambdatest-config.json
          start: npm start
          command: lambdatest-cypress run
          spec: |
            cypress/e2e/e2e testing/Common/*.cy.js
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.f6e78c45-1c38-45b2-b600-a9e54eb54c34 }}
          GITHUB_TOKEN: ${{ secrets.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 }}
